[build]
  publish = "public"
  functions = "netlify/functions"

[build.environment]
  NODE_ENV = "production"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/public/*"
  to = "/:splat"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
